#!/usr/bin/env bash

m0="\x1b[0m"
m1="\x1b[1m\x1b[38;5;204m"
clear="\x1Bc\x1b[3J"
query="${@}"

while [[ ${#query} -lt 1 ]]; do
  echo -ne "${m1}> ${m0}"
  read query
done

endpoint="https://api.dictionaryapi.dev/api/v2/entries/en/$(
  echo "${query}" | sed -e 's: :%20:g'
)"

echo -e "${clear}results for ${m1}${query}${m0}\n"

curl -s "${endpoint}" |
  jq -r '
  .[].meanings[] | 
  "\(.partOfSpeech): \(.definitions[].definition)"
' 2>/dev/null ||
  echo "no results"

tput cup ${LINES}
